### ISSUE TITLE
LSP not working for rust-analyzer

### ISSUE THREAD

**Issue by uncomfyhalomacro** [kakoune-lsp/kakoune-lsp#736]
I have tried `tsserver` and `biome`. I actually don't know why or how `rust-analyzer` on `kak-lsp` version 16.0.0 is not working.

<details><summary>Logs</summary>

```
, module: kak_lsp::editor_transport:138
Mar 18 09:26:18.034 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:60
Mar 18 09:26:18.034 INFO Found project root "/home/uncomfy/development/projects/obs-service-cargo/cargo" because it contains "Cargo.toml", module: kak_lsp::project_root:43
Mar 18 09:26:18.034 DEBG Routing editor request to Route { session: "21536", server_name: "rust-analyzer", root: "/home/uncomfy/development/projects/obs-service-cargo/cargo" }, module: kak_lsp::session:122
Mar 18 09:26:18.034 DEBG Language servers rust-analyzer are still not initialized, parking request, module: kak_lsp::controller:197
Mar 18 09:26:18.036 DEBG From editor:
session  = "21536"
client   = "client0"
buffile  = "/home/uncomfy/development/projects/obs-service-cargo/cargo/src/vendor.rs"
filetype = "rust"
version  = 1
method   = "kakoune/breadcrumbs"
hook = true
[params]
position_line = 58
, module: kak_lsp::editor_transport:138
Mar 18 09:26:18.036 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:60
Mar 18 09:26:18.036 INFO Found project root "/home/uncomfy/development/projects/obs-service-cargo/cargo" because it contains "Cargo.toml", module: kak_lsp::project_root:43
Mar 18 09:26:18.036 DEBG Routing editor request to Route { session: "21536", server_name: "rust-analyzer", root: "/home/uncomfy/development/projects/obs-service-cargo/cargo" }, module: kak_lsp::session:122
Mar 18 09:26:18.036 DEBG Language servers rust-analyzer are still not initialized, parking request, module: kak_lsp::controller:197
```

</details>

**Comment by krobelus** [comment]
How to reproduce?
I see that it picks `/home/uncomfy/development/projects/obs-service-cargo/cargo` as root which might be wrong.
Would need more logs.

> I have tried tsserver and biome

Do those work?

**Comment by uncomfyhalomacro** [comment]
Sorry if I can only use image. So this is a dummy project to test that tsserver and biome works (yes they run together since i configure it like that), and they work as seen from screenshot

![image](https://github.com/kakoune-lsp/kakoune-lsp/assets/66054069/7189d4d2-27c5-44c8-be0f-3bf4ff061468)

**Comment by uncomfyhalomacro** [comment]
> How to reproduce? I see that it picks `/home/uncomfy/development/projects/obs-service-cargo/cargo` as root which might be wrong. Would need more logs.
> 
> > I have tried tsserver and biome
> 
> Do those work?

let me try something

**Comment by uncomfyhalomacro** [comment]
bonk has only one `Cargo.toml`. Behavior the same. I have a feeling this might be something from rust-analyzer and not from kak-lsp

<details><summary>kak-lsp logs on bonk</summary>

```
, module: kak_lsp::editor_transport:138
Mar 18 10:11:39.680 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:60
Mar 18 10:11:39.680 INFO Found project root "/home/uncomfy/development/obs/utilities/bonk/bonk" because it contains "Cargo.toml", module: kak_lsp::project_root:43
Mar 18 10:11:39.680 DEBG Routing editor request to Route { session: "23165", server_name: "rust-analyzer", root: "/home/uncomfy/development/obs/utilities/bonk/bonk" }, module: kak_lsp::session:122
Mar 18 10:11:39.680 DEBG Language servers rust-analyzer are still not initialized, parking request, module: kak_lsp::controller:197
Mar 18 10:11:39.682 DEBG From editor:
session  = "23165"
client   = "client0"
buffile  = "/home/uncomfy/development/obs/utilities/bonk/bonk/src/main.rs"
filetype = "rust"
version  = 1
method   = "kakoune/breadcrumbs"
hook = true
[params]
position_line = 1
, module: kak_lsp::editor_transport:138
Mar 18 10:11:39.682 DEBG Searching for vars starting with KAK_LSP_PROJECT_ROOT_RUST, module: kak_lsp::project_root:60
Mar 18 10:11:39.682 INFO Found project root "/home/uncomfy/development/obs/utilities/bonk/bonk" because it contains "Cargo.toml", module: kak_lsp::project_root:43
Mar 18 10:11:39.682 DEBG Routing editor request to Route { session: "23165", server_name: "rust-analyzer", root: "/home/uncomfy/development/obs/utilities/bonk/bonk" }, module: kak_lsp::session:122
Mar 18 10:11:39.682 DEBG Language servers rust-analyzer are still not initialized, parking request, module: kak_lsp::controller:197
```

</details>

**Comment by uncomfyhalomacro** [comment]
I will check my languages config later. maybe i did an oooopsie there. i will get back after dinner.

**Comment by uncomfyhalomacro** [comment]
It seems the bug is caused by my configuration!

```toml
# [language_server.rust-analyzer]
# filetypes = ["rust"]
# roots = ["Cargo.toml"]
# command = "sh"
# args = [
#     "-c",
#     """
#         if path=$(rustup which rust-analyzer 2>/dev/null); then
#             exec "$path"
#         else
#             exec rust-analyzer
#         fi
#     """,
# ]

[language_server.rust-analyzer]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rust-analyzer"
```

Commented parts were the old config that was not working anymore! This is so weird. I guess I will close it now :D

**Comment by nonk123** [comment]
This almost looks like you don't have `rustup` in your system `PATH` while you do have `rust-analyzer`. Did you install either of these through your system's package manager?

Presumably, you've obtained `rust-analyzer` through your system's package manager (installed to `/usr/bin`) while `rustup` is installed for your user only (somewhere in `~/.local/bin`).

I'm pretty sure the `sh` executable (whatever it stands for on your distro) doesn't source your `.bashrc`, etc. This means that the moment `kakoune-lsp` starts the language-server, `sh` won't look for your user's installation of `rustup`, resulting in the shell script misbehaving (since it's a plain `sh`, the POSIX-compliant shell, rather than something as sophisticated as `bash`).

There are two solutions I can think of:

1. Keep using your current configuration, relying on your system's package manager's `rust-analyzer` (the one in `/usr/bin`, presumably). Not recommended even if you're running rolling-release like Arch; `rustup` is much more reliable with its release schedule and can install `rust-analyzer` for specific Rust versions/toolchains.
2. Install `rustup` system-wide (i.e., through your system's package manager) and keep using the old configuration. The language-server startup script should then work fine since it'll look for `rustup` in `/usr/bin` and run it, which will in turn output the correct path to `rust-analyzer`.

**Comment by uncomfyhalomacro** [comment]
@nonk123 Thanks for the explanation! I use distrobox to install my rustup and rust-analyzer. This configuration was done when rust-analyzer was not yet installed as part of the default rust toolchain. to think that it still worked before is weird tbh until this issue. so i guess i basically just returned to old default configuration.  distrobox exported rust-analyzer and rustup at ~/.local/bin which is added to my PATH.

**Comment by nonk123** [comment]
Interesting. I haven't used distrobox, and that wall of text above was pure speculation based on the info gathered so far. But I'm glad your problem is solved.

I generally would not recommend installing both `rustup` and `rust-analyzer` from the same source since the latter should be installed through `rustup component add rust-analyzer`. This must've been the reason why the language-server startup script got confused since it tried to find the `rustup`-installed `rust-analyzer` first.

At least from my experience, `sh` tends to act differently depending on the distribution. E.g., on Ubuntu Server it's actually symlinked to `dash`. This must've contributed to the problem as well.

**Comment by sclu1034** [comment]
> This almost looks like you don't have `rustup` in your system `PATH` while you do have `rust-analyzer`. Did you install either of these through your system's package manager?

@nonk123 Only if you there's a rather weird shell behind `sh` that cannot handle the script at all. Any regular shell won't care whether the subshell failed with code 1 (rustup didn't find the component) or code 127 (shell didn't find rustup) and will go to the `else` branch in either case.

> I'm pretty sure the `sh` executable (whatever it stands for on your distro) doesn't source your `.bashrc`, etc. 

This doesn't matter here. Environment variables are inherited from parent processes. Kakoune will usually be running as child process of an interactive shell session that does source it, inherit the corresponding `PATH` value and then propagate it further to kakoune-lsp and the `sh` process here.

> At least from my experience, `sh` tends to act differently depending on the distribution. E.g., on Ubuntu Server it's actually symlinked to `dash`. This must've contributed to the problem as well.

For a script as simple as this one, any shell close to POSIX will work. It'd have to be something very different like `fish` to fail completely, which would then violate the accepted standard of `/bin/sh` being a POSIX-compliant shell.

---

@uncomfyhalomacro Running the script from the config manually to see the shell's output would be helpful here. Ideally with `set -x` for extra debugging info.

**Comment by nonk123** [comment]
@sclu1034 thanks for correcting me! I was (and still am) under the influence of 50c supermarket pizza when I wrote that.

> This doesn't matter here. Environment variables are inherited from parent processes. Kakoune will usually be running as child process of an interactive shell session that does source it, inherit the corresponding PATH value and then propagate it further to kakoune-lsp and the sh process here.

You're onto something here. This is most likely related to distrobox since it appears to be wrapping the underlying distros inside a Docker container.

@uncomfyhalomacro how exactly are you starting Kakoune in this case? From the distrobox-issued container? And what are the `~/.local/bin`-exported executables like; are they wrapper scripts for starting the executables inside the container too?

**Comment by uncomfyhalomacro** [comment]
This is weird. it fixed itself... i reused my config and it did the weird.
