### ISSUE TITLE
Extract response from kak-lsp

### ISSUE THREAD

**Issue by mlhhqh** [kakoune-lsp/kakoune-lsp#737]
Is there a way to "hook" into kak-lsp? I want to get the response of the signature help, process it, then insert the result out to the buffer again.
Calling the following (as expected) just shows the signature tooltip inside kakoune:

`define-command mytest -docstring "test func" %{
    lsp-signature-help
}`

**Comment by nonk123** [comment]
> Calling the following (as expected) just shows the signature tooltip inside kakoune:

This behavior appears to be hardcoded; see [here](https://github.com/kakoune-lsp/kakoune-lsp/blob/3ce79a4c3c3059f086214f3c8f3214401989ac2e/src/language_features/signature_help.rs#L134).

I don't think you can do much without e.g. changing the output command from `lsp-show-signature-help` to your own in the Rust code.

You might be able to do it conditionally by adding a parameter [here](https://github.com/kakoune-lsp/kakoune-lsp/blob/3ce79a4c3c3059f086214f3c8f3214401989ac2e/rc/lsp.kak#L1126) and hooking even deeper into the server's code.

**Comment by krobelus** [comment]
> I want to get the response of the signature help, process it, then insert the result out to the buffer again.

Interesting idea; not sure if signature help is the right request to do this, I use the snippets provided by the language server. When I accept the completion of a function name, it will also insert placeholders into the buffer that have the same text as in the signature help.
Normally I use `<tab>` (per [recommended mappings](https://github.com/kakoune-lsp/kakoune-lsp#configure-mappings)) to replace all the placeholders, but I sometimes also use `<esc>` to keep them. Other editors use a similar behavior.
Which language server are you using? Is there a scenario where completion snippets don't work?

**Comment by mlhhqh** [comment]
The signature help was just an example  since it's the easiest example to visualize I would assume. Changing some key bindings I cannot process the response (for example the signature of the function) externally and then write it into the buffer.

I guess the only way is to fork kak-lsp and dive into the Rust side.

**Comment by krobelus** [comment]
Anything is possible, the hard part is defining an output format that is usable. I have no idea which one you want.
It's not as simple as giving a list of parameter names because not every language uses `,` as separators.
Each parameter includes a label, which includes the type, so that's not really suitable for insertion

The point of kak-lsp is to be a CLI wrapper around LSP. But we can't easily provide what's not in LSP.
Of course if there is a reasonable use case we can add some hacks to make it work, and eventually standardize it.
But the hard part is designing it. What would the user interface be? A `lsp-insert-default-arguments` command?

Note that we had `lsp-connect` (it was recently removed but should be easy to `git revert`) which should fit the bill.
However don't believe it's very useful. I don't think anyone used it. You can use it to do your thing; but it's also easy to do it on the Rust side, once you got the hang of it.

**Comment by krobelus** [comment]
> simply returns the JSON output of the LSP server unprocessed.

yeah `lsp-connect` does exactly that. Would be interesting to see if it's useful. I did build an `echo-current-toplevel-symbol` command which has only recently been obsoleted by modeline breadcrumbs. I don't remember if it had problems.
You'd need to revert c08c194 (Remove lsp-connect, 2024-03-11).
A usage example is documented in the original commit message 04b27ea (Introduce lsp-connect to allow users to handle raw LSP responses, 2022-02-13)
