### ISSUE TITLE
'rename-client': client name 'global' is not unique

### ISSUE THREAD

**Issue by chriselrod** [kakoune-lsp/kakoune-lsp#738]
When the server starts, I often get extra terminals appearing, with this message. It doesn't seem to be a big deal: I close the extras, and am left with a working client window that shows lsp diagnostics and documentation.

I suspect this happens because I have multiple separate kakoune servers -- one per git repo I'm editing -- and kak-lsp tries to use the same `global` client name for each one?

I have
```
lsp-auto-hover-enable global
```
in my kak config, which normally typically resulted in 1 such window.
Adding
```
lsp-inlay-diagnostics-enable global
```
resulted in a second such window (without doing anything as far as I can tell).

As an aside, I tend to use a kak client for displaying the LSP's info because the hover text just sits at the bottom of the window, preventing me from being able to see the bottom part of the file.
Adding a ton of new lines works briefly, but it's annoying to constantly add them (the formatter will clean them up, which is both good and bad).

**Comment by krobelus** [comment]
> I have multiple separate kakoune servers -- one per git repo I'm editing 

Same but your `%opt{lsp_cmd}` likely contains `s <kakoune-session-name>` which means that the kak-lsp server is scoped to a single Kakoune session, so there is no crosstalk.

> lsp-auto-hover-enable global

(Since the argument is not a scope but a client name "global" is surprising.)

I can reproduce, it seems to be spawning an indefinite number of clients.
The command creates a new client which triggers the same hook recursively.
The `terminal` command which underpins `new` is async, that's why we `rename-buffer` is racing.

Overall I think this command is too complex, we should try to simplify the interface.

I think that the user should be in charge of creating the hover client (given that they already need to create toolsclient if they use that).
It's somewhat awkward that `lsp-auto-hover-enable` takes a hardcoded client name because that
technically requires [`ClientRename` hooks](https://github.com/mawww/kakoune/pull/5133) for us to implement correctly.
I'm not sure if the argument is even necessary because we already default to `%opt{docsclient}`

I think the original reason why `lsp-auto-hover-enable` takes a client name was for consistency with `lsp-hover-buffer`;
that's the one I've used for testing and it seemd reasonable to be able to pass a client name in interactive scenarios.
I don't think it ever made much sense to pass a fixed client name to `lsp-auto-hover-enable` client names should be able to change freely.
It should just be a matter of `set g docsclient %val{client}` to have the hover info display somewhere else.

**Comment by krobelus** [comment]
ed077c8bdb9b75300e2d63fd64e9aaf640dd23d9 is a quick step towards improving this.
I'm not sure if the interface is ideal because now it forces you to define a docsclient if you use `lsp-auto-hover-buffer-enable`.
I personally would create a command that does both in lockstep (setting a docsclient and enabling autohover) but it really depends on the workflow

**Comment by krobelus** [comment]
I guess we should silence the new error when running from a hook.. need to think about it

I personally never use auto hover, I use the `h` shortcut in the `lsp` user mode.

**Comment by krobelus** [comment]
I've pushed another commit to simplify the usage.
Now you can use `lsp-auto-hover-buffer-enable`,
then do something like `new buffer *hover*`.
Moving the cursor in the original client will update the hover buffer in the new client.

Or you can set the `docsclient` option, that works too

**Comment by chriselrod** [comment]
Thanks for the prompt responses!
I've been trying `lsp-auto-hover-enable` these past few days, but am switching to `lsp-auto-hover-buffer-enable` now.

> Same but your %opt{lsp_cmd} likely contains s <kakoune-session-name> which means that the kak-lsp server is scoped to a single Kakoune session, so there is no crosstalk.

Yes. I didn't define `lsp_cmd`, so I'm using the default value.
```
rc/lsp.kak
5:declare-option -docstring "Command with which lsp is run" str lsp_cmd "kak-lsp -s %val{session}"
```

> I think that the user should be in charge of creating the hover client (given that they already need to create toolsclient if they use that).


> I've pushed another commit to simplify the usage.
Now you can use `lsp-auto-hover-buffer-enable`,
then do something like `new buffer *hover*`.
Moving the cursor in the original client will update the hover buffer in the new client.

Okay, I think that's reasonable.
Getting to be a little more deliberate about when I open clients is nice.

I confess that I don't know when `docsclient` and `toolsclients` are options. I hadn't been using them/don't know about them. I'd always been using the LSP for docs (+diagnostics), and things like grep results showing up in the current client seems fine.
