### ISSUE TITLE
Feature Request: Support modifying CodeActionContext

### ISSUE THREAD

**Issue by sagehane** [kakoune-lsp/kakoune-lsp#742]
### What is it?

LSP supports specifying a CodeActionContext[0][1] to filter for particular types of code actions. This could (and in my opinion, should) replace `kak-lsp`'s current approach of using regex to filter code actions by title.

### Use case

idris2-lsp[2] is an example of a LSP server that expects code action filter support in order to bind specific code actions to keybinds.

There's a culture in the community to bind certain keys to specific code actions[3], and the way in which idris2-lsp supports that is by filters.

### Status quo and its limitations

Currently, it's possible to use `lsp-code-actions` to get a list of all supported code actions for a given cursor position. If trying to narrow down supported code actions, `lsp-code-action <pattern>` can be used to narrow down the code action by title.

There are a few issues with this:
1. Devising a regex to properly match the relevant code action can be difficult (idris2-lsp can offer multiple candidates of the same type of code actions)
2. The title of a code action might be unstable; projects might not even document them well
3. Regex is arguably complex and slow
4. When there are multiple matching actions, `kak-lsp` gives up instead of listing all matches (seems to be an implementation issue)

I think the current approach is quite hacky and worth deprecating, but that's probably something worth discussing in a different issue.

[0] - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionParams
[1] - https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionContext
[2] - https://github.com/idris-community/idris2-lsp?tab=readme-ov-file#code-actions-filters
[3] - https://docs.idris-lang.org/en/latest/tutorial/interactive.html#interactive-editing-in-vim

**Comment by krobelus** [comment]
Interesting, I didn't know about `codeActionParams.only`. We can probably add that as arguments to `lsp-code-actions`.

> When there are multiple matching actions, kak-lsp gives up instead of listing all matches (seems to be an implementation issue)

the original motivation for this was to run a code action on save. For that case failing on ambiguous matches seemed to be the safest option but I think in practice it's fine to make it execute all matching code actions.

> I think the current approach is quite hacky and worth deprecating,

Yeah, maybe deprecate `lsp-code-action` and (in addition to the aforementioned changes) give `lsp-code-actions` the expected behavior if called from a hook context, so skip the menu and immediately execute all matching actions.

On the LSP codeActionContext names versus regex, I think it's a tradeoff.
I don't agree with "Regex is arguably complex and slow" and the upside of regex is that you can make things work even without docs.
But I see your points; title isn't meant to be stable / suitable for matching.
Also I have never composed such a regex interactively (the menu is much easier).
It would be really nice if LSP provided a list of possible filters like `refactor.rewrite.CaseSplit`,
then we could use that as completions for `lsp-code-actions`.
Then there would be pretty much no reason to use regex here.

**Comment by sagehane** [comment]
>I think in practice it's fine to make it execute all matching code actions.

This might potentially be desirable in very specific cases but I think it would be nonsense in most cases.

What if multiple code actions modify the same portion of text? These code actions would be conflicting with each other and hence impossible to apply. Back to the Idris example, most of these code actions do introduce things that would be conflicting with each other and the point is to have the programmer decide which one to apply.

**Comment by sagehane** [comment]
Also, since this is probably a good time to specify the feature I want, I think it would be nice to have a flag that makes the menu prompt even if a filtered code action has only one candidate. With that `ExprSearch` example above, maybe I don't want to apply the suggestion even in cases where there's only one candidate that Idris2 offers.

**Comment by krobelus** [comment]
> This might potentially be desirable in very specific cases but I think it would be nonsense in most cases.

yeah that makes sense. VSCode has something called codeActionsOnSave, need to check how they select actions.
But it sounds like for the hook case we can simply keep failing if the match is ambiguous, that would cover existing use cases.

>  I think it would be nice to have a flag that makes the menu prompt even if a filtered code action has only one candidate

yeah that's the existing behavior, of `lsp-code-actions`, no plans to change that

**Comment by sagehane** [comment]
There are some actions like `CaseSplit` where there's ever only one code action suggestion and it would be nice to be able to run it without the menu ever starting.

**Comment by krobelus** [comment]
should be done. Also there's `lsp-code-actions -auto-single` for skipping the menu.
One thing that's not clear is if/how we can should the code action kinds for each concrete code action.
Showing them in the menu next to the title is probably too noisy. I guess we could have a `lsp-code-actions -verbose` switch, not sure

**Comment by sagehane** [comment]
I gave it a test. Works great so far, thank you.
