### ISSUE TITLE
When not leaving insert mode, the insert after autocomplete marker does not get cleaned up.

### ISSUE THREAD

**Issue by slatian** [kakoune-lsp/kakoune-lsp#770]
When kak-lsp suggests something like a function name and the suggestion contains an ellipsis `…` there is this (by default) green marker that indicates which test will be replaced if one would start typing now.

The problem is that this marker doesn't vanish until one leaves insert mode, which causes problems the second time the feature is used (since switching to insert mode), because now it makes my cursor jump to the previous location I used the autocomplete on and even deletes the code that was under the marker.

Expected behavior for me would be the the marker vanished as soon as I start typing.

Leaving and going back into insert mode resets the marker as expected.

My configuration is optimized to require relatively few mode switches when just writing code, so this is quite an annoyance.

**Comment by krobelus** [comment]
Thanks for reporting. Here my brain dump, I'll attempt a fix later.

> because now it makes my cursor jump to the previous location I used the autocomplete on

Ok so just so I understand: given 

```rust
fn foo(i: i32, j: i32) {}
```

you type something like

	`foo<c-n>1<end>;<ret>foo<c-n>2`

which breaks as you described because there is a snippet placeholder
left in the first line, and we jump to that one instead of the one we just added.
(Snippet placeholders are always visited in the order they appear in the buffer. I believe this was mostly because it simplified implementation, maybe we should try again).

The intended use case for having multiple sets
of snippets is nested function calls: if I type
`foo<c-n>foo<c-n>1<tab>2<tab>3<tab>;` (using the [recommended
mapping for `<tab>`](https://github.com/kakoune-lsp/kakoune-lsp?tab=readme-ov-file#configure-key-mappings))
then I get

	foo(foo(1, 2), 3);

I use this sometimes and would prefer to keep it but I appreciate the breakage and also the fact that it's not really useful without the recommended mapping.

OTTOMH, there are 2 things one can do:
- you can turn off snippet support (`set g lsp_snippet_support false` on latest master, else if you have a `kak-lsp.toml` change it there).
  Then the language server will no longer send completions with placeholders. IIRC there was a case where this caused less completions to be sent but that'd be a bug in the language server.
- Since the "multiple concurrent sets of placeholders" use case is primarily intended for nested functions,
  perhaps we can try to detect weird cases like the first one I described, and clear placeholders automatically.
  The criteria I have in mind is "if any of the new placeholders is positioned after an existing placeholders, clear existing ones".
  This should not obstruct any legit use of nested snippets, because placeholders are always visited in order (and each placeholder is cleared as it's visited).
  Let me know if this criteria works for your cases.

**Comment by krobelus** [comment]
```diff
diff --git a/rc/lsp.kak b/rc/lsp.kak
index 855e0d25..876b28fb 100644
--- a/rc/lsp.kak
+++ b/rc/lsp.kak
@@ -2731,6 +2731,23 @@ use Text::ParseWords();
 
 my @sel_content = Text::ParseWords::shellwords($ENV{"kak_quoted_selections"});
 my @existing_placeholder_ids = split(/ /, $ENV{"kak_opt_lsp_snippets_placeholder_groups"});
+my @existing_placeholders = split(/ /, $ENV{"kak_opt_lsp_snippets_placeholders"});
+my @selections_desc = split(/ /, $ENV{"kak_selections_desc"});
+
+if (scalar @existing_placeholders > 1) {
+    $existing_placeholders[1] =~ m{^(\d+)\.(\d+)} or die "failed to parse: $existing_placeholders[1]";
+    my $existing_line = $1;
+    my $existing_column = $2 ;
+    $selections_desc[0] =~ m{^(\d+)\.(\d+)} or die "failed to parse: $selections_desc[0]";
+    my $new_line = $1 ;
+    my $new_column = $2 ;
+    if ($new_line > $existing_line || ($new_line == $existing_line && $new_column > $existing_column)) {
+        print "
+            set-option window lsp_snippets_placeholders
+        ";
+        @existing_placeholder_ids = ();
+    }
+}
 
 my @placeholder_defaults;
 my %placeholder_id_to_default;
```

that should fix one case.
But I see that it's not ideal.
I think we can also clear all placeholders when the user does anything other than inserting text.
So for example arrow keys can clear the placeholder. Would that help your case?

**Comment by slatian** [comment]
Thanks for the quick reply.

How I get into this situation:

Usually I have something like an half finished match block:

```
match self {
    A => 
    B =>
}
```
I Start typing after A: `foo<c-n>1<tab>2<down>foo<c-n>3…`

I press `<down>` because I'm finished with A and want to switch over to B as quick as possible.

What I didn't realize is that the left over marker is intended for tabbing out of he function. (I'm pretty new to using kakoune with kak-lsp).

And blindly clearing on a new autocomplete breaks nesting, which makes sense.

Arrow keys clearing the placeholders will probably break other peoples workflow.

What do you think about clear all markers for any navigation that results in any (end) marker not having a cursor before of it? That should even work for multi-cursor scenarios.

**Comment by krobelus** [comment]
> What do you think about clear all markers for any navigation that results in any (end) marker not having a cursor before of it? That should even work for multi-cursor scenarios.

Yeah that sounds right, I forgot about the multi-cursor case.
I ended up committing the fix for single selections for now because I didn't get around to multi-selections yet (looks like those had a pre-existing bug which I would want to fix first)

LMK if you keep having issues.
Note that rust-analyzer provides a "Fill match arms" code action, so you can hit `<space>la` (with the recommended bindings) on the match statement to autofill match arms.
