### ISSUE TITLE
LSP configuration, possibility to send long list of settings (containing JSON schemes)

### ISSUE THREAD

**Issue by Release-Candidate** [kakoune-lsp/kakoune-lsp#797]
I succeeded to configure the JSON LSP using the following stanza with the scheme for `package.json`:

```text
hook -group lsp-filetype-json global BufSetOption filetype=json %{ 
   set-option buffer lsp_servers %{    
        [vscode-json-language-server] 
        root_globs = ["package.json"] 
        args = ["--stdio"]  
        settings_section = "json"  
        [vscode-json-language-server.settings.json]
        provideFormatter = true
        [[vscode-json-language-server.settings.json.json.schemas]] 
        fileMatch = ["/package.json"]   
        url = "https://json.schemastore.org/package.json"
        [vscode-json-language-server.settings.json.json.format]
        enable = true
        [vscode-json-language-server.settings.json.json.validate]
        enable = true 
     }         
}
```

See LSP documentation at https://github.com/microsoft/vscode/blob/main/extensions/json-language-features/server/README.md#settings

The problem is the `vscode-json-language-server.settings.json.json.schemas` array is **big** (1000 elements), something like that JSON that Sublime Text's LSP package uses: https://github.com/sublimelsp/LSP-json/blob/master/lsp-json-schemas.json

How to I best send something like the above linked JSON to the LSP?

**Comment by krobelus** [comment]
there should be no problem with including it in `lsp_servers` unless it's huge (many MB probably).
If you notice any slowness, LMK. You can check by running something like `kak -debug 'shell|commands|profile'` to see if anything is taking like >20ms or so.

you'll need to use some tool like `yq` to convert from JSON to TOML.
Making `lsp_servers` accept JSON might be nice but it's not clear what the UI should look like.

Overall, I think that server specific configuration as part of the editor configuration should be avoided because it adds a lot of duplicated effort.
I'd rather use a configuration file that is read by JSON LSP no matter which editor is talking to it. Then there is no need to do the same for every single editor. That just makes things harder for all but the most popular editor.

**Comment by Release-Candidate** [comment]
Thanks, will do. And no, I don't understand why vscode-json-language-server doesn't have its own list of schemas, as its borderline useless without them.

Oh, btw. I don't think I should add the whole list to the "official" `servers.kak` in a PR, but at least the `format` and `validate` options and some schemas, like the one for `package.json`. And add a link to some(?) example lists in  a comment, I guess.

I'm going to configure the CSS and HTML LSP too, there are many options missing to make them useful. The Sublime Text settings at https://github.com/sublimelsp/LSP-html/blob/master/LSP-html.sublime-settings and https://github.com/sublimelsp/LSP-css/blob/master/LSP-css.sublime-settings are a good template.

**Comment by krobelus** [comment]
sounds good, thanks. Hopefully we can improve the upstream defaults as well. The problem might be that VSCode doesn't care if defaults are bad because there is always an accompanying VSCode plugin that can do that.. might be worth looking for issues or opening one

**Comment by Release-Candidate** [comment]
Took me a bit longer than anticipated ;), but here it is: https://github.com/kakoune-lsp/kakoune-lsp/pull/800
